autoencoder:
  class: Autoencoder1D
  model:
    attn_per_block: 12
    block_out_channels:
    - 512
    embed_dim: 32
    embedding_channels: 16
    ff_mult: 4
    img_height: 128
    in_channels: 1
    n_embed: 2048
    z_channels: 32
  train:
    batch_size: 16
    checkpoint_every: 1000
    data_path: ../data/lakh_giant_midi_prmat1c_8bin_lmdb
    gradient_accumulation_steps: 2
    gradient_clip_val: 1.0
    learning_rate: 0.0001
    logger_kwargs:
      entity: rainbow_tensor
      id: null
      log_model: all
      project: music_diffusion
    lr_warmup_steps: 1000
    mixed_precision: 'no'
    num_epochs: 50
    resume: false
    save_dir: ./models
    save_name: autoencoder
music_diffusion:
  class: MusicDiffusion
  model:
    blocks:
    - 6
    - 8
    - 8
    c_hidden:
    - 512
    - 1024
    - 1024
    c_in: 256
    c_out: 256
    c_r: 64
    dropout: 0.1
    kernel_size: 3
    level_config:
    - CT
    - CTA
    - CTA
    n_classes: 6
    nhead:
    - -1
    - 16
    - 16
    num_labels: 2048
    patch_size: 2
    self_attn: true
  train:
    batch_size: 4
    checkpoint_every: 1000
    data_path: ../data/lakh_giant_midi_prmat1c_8bin_lmdb
    gradient_accumulation_steps: 2
    gradient_clip_val: 1.0
    learning_rate: 0.0001
    logger_kwargs:
      entity: rainbow_tensor
      id:
      log_model: all
      project: music_diffusion
    lr_warmup_steps: 500
    mixed_precision: 'no'
    num_epochs: 50
    resume: false
    save_dir: ./models
    save_name: diffusion_model
